### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by oknoorap** [MironowDW/Crossword#1]
Is there any documentation @MironowDW

**Comment by MironowDW** [comment]
@oknoorap no, only demo https://github.com/MironowDW/Crossword/tree/master/demo

**Comment by oknoorap** [comment]
I have some questions:
- Can I generate with static position (no randomize row/column every refresh)
- If I set type to TYPE_BASE_LINE_COLUMN, can I have multiple columns base?

Thank you.

**Comment by MironowDW** [comment]
No and no. i can do with, but not fast )

**Comment by oknoorap** [comment]
okay thanks
